{% set version = "0.16.1" %}
{% set cov_fail_under = "87" %}
{% set min_sphinx = "6.1" %}

package:
  name: pydata-sphinx-theme
  version: {{ version }}

source:
  - url: https://pypi.io/packages/py3/p/pydata-sphinx-theme/pydata_sphinx_theme-{{ version }}-py3-none-any.whl
    sha256: 225331e8ac4b32682c18fcac5a57a6f717c4e632cea5dd0e247b55155faeccde
  - folder: src
    url: https://github.com/pydata/pydata-sphinx-theme/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 494f9827c7cf07f412cbb1711149e02f56a9ea05ed58ac781720b150a0f8b22f

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install --find-links . --no-index --ignore-installed --no-deps pydata-sphinx-theme
    - cd {{ RECIPE_DIR }} && {{ PYTHON }} collect_licenses.py

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
    - sphinx-theme-builder >=0.2.0a7
  run:
    - accessible-pygments
    - babel
    - beautifulsoup4
    - docutils !=0.17.0
    - packaging
    - pygments >=2.7
    - python >=3.9
    - sphinx >={{ min_sphinx }}
    - typing_extensions

test:
  source_files:
    - src/tests
  imports:
    - pydata_sphinx_theme
  commands:
    - pip check
    - cd src/tests
    - coverage run -m --source=pydata_sphinx_theme --branch pytest -vv --color=yes --tb=long -k "not (pygments_fallbacks or translations)"
    - coverage report --show-missing --skip-covered --fail-under={{ cov_fail_under }}
  requires:
    - jupyter_sphinx
    - numpydoc
    - pandas
    - pip
    - plotly
    - pytest-cov
    - pytest-regressions
    - recommonmark
    - sphinx {{ min_sphinx }}.*
    - sphinx-thebe
    - xarray

about:
  home: https://github.com/pydata/pydata-sphinx-theme
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - src/LICENSE
    - third-party-licenses/
  summary: Bootstrap-based Sphinx theme from the PyData community
  doc_url: https://pydata-sphinx-theme.readthedocs.io/
  dev_url: https://github.com/pydata/pydata-sphinx-theme

extra:
  recipe-maintainers:
    - jorisvandenbossche
    - bollwyvl
    - michaelweinold
